### ISSUE TITLE
Get Complex numbers to work without compromises

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4835]

**Comment by casella** [comment]
Original ticket: https://trac.openmodelica.org/OpenModelica/ticket/4835

**Comment by casella** [comment]
Still pending issues:
- [ ] Operator overloading fails for matrices [#2387](https://trac.openmodelica.org/OpenModelica/ticket/2387)
- [ ] Problems with functions returning matrices of Complex operator records [#4611](https://trac.openmodelica.org/OpenModelica/ticket/4611)
- [ ] Sliced subscripts in Modelica.ComplexMath.sum fails at code generation [#5885](https://trac.openmodelica.org/OpenModelica/ticket/5885)

**Comment by mahge** [comment]
@perost has added an implementation for handling #5885 (and slices in general) in #8339. It has potentially fixed #5885 and #8306 (all models from BLDC simulate).

We still need some more work for handling slices on the right hand side of assignments but we can do that after the holidays.
