### ISSUE TITLE
Plan for 1.18.0 release

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7561]
This ticket lists the issues that must be fixed before releasing 1.18.0, preferably before branching off

- [x] #7500 OMEncrypted bug allows loading libraries for which you have no license
- [x] #7502 OMEncrypted bug allows loading sub-libraries for which you have no license
- [x] #7548 Reinstate non-standard FMI export of clocked FMUs under flag for ABB
- [x] #7517 Improved handling and documentation of global vs. local simulation settings in OMEdit
- [x] #7546 PR should be reviewed and merged in
- [x] [OMLibraries #10](https://github.com/OpenModelica/OMLibraries/pull/10) should be merged in.
- [x] #7545 Resizing an object in OMedit will cause broken-number coordinates
- [x] #7551 OpenModelica -cpu flag does not work for 1.18.0~dev-320-g1a21771-1
- [x] #7596 Fix latest commits that broke down PowerSystems
- [x] #7534 Allow selection of static linking in Windows from OMEdit and via a compiler flag

These issues should preferably fixed and back-ported to 1.18.0 maintenance before the release.

- [x] [#5839](https://trac.openmodelica.org/OpenModelica/ticket/5839#comment:12) Plotting with toggled sign
- [x] [#5849](https://trac.openmodelica.org/OpenModelica/ticket/5849#comment:35) Automatic elimination of blank areas
- [x] [#5447](https://trac.openmodelica.org/OpenModelica/ticket/5447#comment:34) issues with unit prefixes in OMEdit plots
- [ ] [#6267](https://trac.openmodelica.org/OpenModelica/ticket/6267#comment:18) regression with arrays of parameters affecting Buildings and ThermoPower
- [ ] [#6196](https://trac.openmodelica.org/OpenModelica/ticket/6196#comment:15) fix `--tearingStrictness=strict` to avoid issue with bogus linear tearing in AC power system models
- [ ] [#6342](https://trac.openmodelica.org/OpenModelica/ticket/6342) Select the sparse solver when appropriate
- [ ] #7508 Regressions due to reshuffleLoops
- [ ] #7536 fix event handling in `delay()` by reusing code from spatialDistribution
- [X] #6419 Too many events during initialization due to bug in nonlinear homotopy solver
- [ ] #7578 OMEncrypted removes connections when loading libraries
- [x] #7579 Issue with index reduction or arrays (?)
- [x] #7627 Impossile to change the legend of three curves
- [ ] #7720 Fix drControl tutorial

**Comment by rfranke** [comment]
#7548, #7546 and #7596 are solved. The latter makes PowerSystems work as before.

It would be good to add #7579 (BackendDAEEXT.getAssignment failed) to the list. This must be a small thing / missing check in the index reduction algorithm. This affects 4 examples of PowerSystems, besides #7579.

**Comment by max-privato** [comment]
I would also recommend #7627, since it is due to a clear bug that should be very easy to spot and fix. 
To ease understanding (and possibly fixing) this issue, today I've improved the ticket's description.

**Comment by casella** [comment]
@max-privato, done already 😄

**Comment by max-privato** [comment]
wow!

**Comment by casella** [comment]
1.18.0 was released on Sep 4 2021
