### ISSUE TITLE
Finalize library handling in 1.19.0

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8671]
- [x] For Windows: remove all optional libraries from the installer, since they will be obtained via the package manager
- [x] For Windows: leave MSL 3.2.3 and MSL 4.0.0 in the installer, on by default but with possibility to deactivate, if one wants. Install them in the Program Files directory. This ensures that OMEdit includes the MSL out of the box without the need of further actions, also in the case of weird APPDATA path with accented letters
- [x] For Windows: change the order of priority of MODELICAPATH, so it looks in the APPDATA directory first, and then in the Program Files as a fallback option
- [x] Do not load any library by default in Options | Libraries
- [x] Change the text of the Options | Libraries window from "System Libraries" (which is confusing) to "Libraries loaded automatically upon starting OMEdit"
- [x] Remove initial splash screen with obsolete library explanation
- [X] Add buttons for loading and installing libraries to the Welcome | Recent files window (PR #8665)
- [x] Remove the "Keep using new front-end" pop-up window, which is now completely obsolete, the new front-end is good enough. See #8670.
- [x] Change File | Upgrade installed libraries into File | Update installed libraries, which better describes what it does
- [x] Add dialog to File | Update installed libraries explaining what it does, because otherwise OMEdit hangs for a long time, particularly in case of shaky internet connection, which is not nice
- [x] Make sure that the class loader in loadModel() and loadFile() uses the same priority rules as the package manager and loads the right library when there are multiple ones available that fit the uses annotation, see #8060.
- [x] Make sure that the library conversion in OMEdit works as expected. A small MWE is available [here](https://github.com/OpenModelica/OpenModelica/discussions/8726#discussioncomment-2410475), we may try some bigger ones before releasing the software
- [x] Make sure that library conflicts are reported and handled correctly, see #8183

**Comment by adeas31** [comment]
@casella I am done with the tasks that I can handle.

> Add button "Help" to Welcome | Recent files windows pointing to relevant section of the User's Guide

Adding a help button just for recent files window is probably not very helpful. It might create more confusion rather than helping the users. My suggestion is to not add a Help button.

**Comment by casella** [comment]
> @casella I am done with the tasks that I can handle.

Good. I'll check everything ASAP and report.
 
> Adding a help button just for recent files window is probably not very helpful. It might create more confusion rather than helping the users. My suggestion is to not add a Help button.

OK. Let's see what is the feedback (if any) from users.

**Comment by casella** [comment]
@adeas31 regarding #8183, currently you get a (wrong) scripting warning, that should of course be fixed. But then, OMEdit needs to pick it up and proceed [as I suggested](https://github.com/OpenModelica/OpenModelica/issues/8183#issuecomment-1078524550), if you think this makes sense.

How should we proceed?

**Comment by casella** [comment]
> @adeas31 regarding #8183, currently you get a (wrong) scripting warning, that should of course be fixed. But then, OMEdit needs to pick it up and proceed [as I suggested](https://github.com/OpenModelica/OpenModelica/issues/8183#issuecomment-1078524550), if you think this makes sense.

This is now resolved.

**Comment by casella** [comment]
All tasks done.
