### ISSUE TITLE
Handle decimals in correctly and consistently in all contexts

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8865]
On several occasions, OMC returns outputs with badly rounded decimals, whenever the float representation of the decimal number is not exact, for example
- [x] when returning flat Modelica output (see MWE in #7465)
- [x] when converting non-SI displayUnit parameter inputs to SI-units values in OMEdit (see #8860, #8062, and #12003)
- [x] when converting default SI parameter values in non-SI display units (see MWE in #7491)
- [x] when displaying parameter values in the variables browser (see MWE in #10476)

The issue was discussed extensively in #7465, with a proposal to use the routines in the [Ryu library](https://github.com/ulfjack/ryu), that was designed specifically to avoid this kind of issues. We should
- embed this functionality in an API call
- use it in the the three above-mentioned contexts, and others should they arise

**Comment by casella** [comment]
Moving this to 1.23.0, this change is simply too involved to put in 1.22.1 in a safe way.

**Comment by abuntrock** [comment]
@casella Thanks for the clarification. We are looking forward to 1.23.0 then

**Comment by casella** [comment]
Status update:
- All issues are fixed in the Linux 1.23.0 nightly builds.
- There is a remaining issue on Windows that will be fixed as soon as we merge PR #10939 on master
- All fixes will be available in release 1.23.0 around April 2024

Unfortunately it was not really possible to back-port this to 1.22.2 which will be out soon. Too much stuff to change.

**Comment by casella** [comment]
All remaining issues should be fixed by #12052.

**Comment by casella** [comment]
Still issues with #12004 and #12009.

**Comment by casella** [comment]
All issues should be solved now.

**Comment by abuntrock** [comment]
Thanks a lot for fixing this issue. This is an important achievement for us at Rexroth :)
